version: '3'
services:
  web:
    container_name: rfi_vulnerability_scenarios
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9004:80
    volumes:
      - ./src/:/var/www/html/
    image: moeinfatehi/rfi_vulnerability_scenarios:latest